default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: db

development:
  <<: *default
  database: counter_app_development

test:
  <<: *default
  database: counter_app_test

production:
  <<: *default
  database: counter_app_production
